#                                                                        #
# Security policy definition                                             #
#                                                                        #
# Settings for the Events package                                        #
Org:
  Gucken:
    Events:
      views:
        bielefeld:
          layoutRootPath: resource://Org.Gucken.Bielefeld/Private/Layouts
          templateRootPath: resource://Org.Gucken.Bielefeld/Private/Templates
          partialRootPath: resource://Org.Gucken.Bielefeld/Private/Partials
          skinPackage: Org.Gucken.Bielefeld
